CaseloadManager/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CaseloadManager.Models
{
    public class Client
    {
        [Key]
        public int ClientId { get; set; }

        [Required]
        [Display(Name = "Initial")]
        public string FirstInitial { get; set; }

        [Required]
        [MaxLength(25)]
        [MinLength(1)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [NotMapped]
        [Display(Name = "Full Name")]
        public string FullName
        {
            get
            {
                return $"{FirstInitial}. {LastName}";
            }
        }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Birthdate")]
        public DateTime Birthdate { get; set; }

        [RegularExpression(@"^[a-zA-Z  0-9]*$", ErrorMessage = "No special characters.")]
        [Display(Name = "Diagnosis")]
        public string Diagnosis { get; set; }

        
        [Display(Name = "Sessions Per Week")]
        public int? SessionsPerWeek { get; set; }

        [Required]
        [Display(Name = "Status")]
        public int StatusTypeId { get; set; }
        [Display(Name = "Status")]
        public StatusType StatusType { get; set; }

        [Required]
        [Display(Name = "Facility")]
        public int FacilityId { get; set; }
        public Facility Facility { get; set; }

        [Required]
        public ApplicationUser User { get; set; }

        [Required]
        public string UserId { get; set; }

        public virtual ICollection<TherapySession> TherapySessions { get; set; }
        public virtual ICollection<ClientAssessment> ClientAssessmets { get; set; }
        public virtual ICollection<Goal> Goals { get; set; }
        
    }
}

CaseloadManager/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CaseloadManager.Data;
using CaseloadManager.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace CaseloadManager.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public ClientsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Clients
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.StatusSortParm = String.IsNullOrEmpty(sortOrder) ? "status" : "";
            ViewBag.FacilitySortParm = String.IsNullOrEmpty(sortOrder) ? "facility" : "";
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var clients = from c in _context.Clients.Include(c => c.StatusType)
                .Include(c => c.User)
                .Include(c => c.Facility)
                .Where(c => c.UserId == user.Id)
                          select c;
            switch (sortOrder)
            {
                case "name_desc":
                    clients = clients.OrderByDescending(c => c.LastName);
                    break;
                case "status":
                    clients = clients.OrderBy(c => c.StatusTypeId);
                    break;
                case "facility":
                    clients = clients.OrderBy(c => c.Facility);
                    break;
                default:
                    clients = clients.OrderBy(c => c.LastName);
                    break;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(p => p.LastName.Contains(searchString));
            }

            return View(await clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = new ClientEditViewModel();

            viewModel.ClientAssessments = await _context.ClientAssessments
               .Include(c => c.Client)
               .ThenInclude(Client => Client.StatusType)
               .Include(c => c.Client)
               .ThenInclude(Client => Client.User)
               .Include(c => c.Client)
               .ThenInclude(Client => Client.Facility)
               .Include(c => c.Assessment)
               .Include(c => c.Client)
               .ThenInclude(Client => Client.Goals)
               .Include(c => c.Client)
               .ThenInclude(Client => Client.TherapySessions)
               .Where(c => c.ClientId == id).ToListAsync();

            viewModel.Client = await _context.Clients
                    .Include(c => c.StatusType)
                    .Include(c => c.User)
                    .Include(c => c.Facility)
                    .FirstOrDefaultAsync(c => c.ClientId == id);


            ViewBag.HasAssessment = "true";
            ViewBag.HasGoal = "true";

            if (viewModel.ClientAssessments.Count == 0)
            {
                ViewBag.HasAssessment = "false";
                viewModel.Client = await _context.Clients
                    .Include(c => c.StatusType)
                    .Include(c => c.User)
                    .Include(c => c.Facility)
                    .FirstOrDefaultAsync(c => c.ClientId == id);
            }

            return View(viewModel);
        }

        // GET: Clients/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            ViewData["StatusTypeId"] = new SelectList(_context.StatusTypes, "StatusTypeId", "Name");
            //ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");

            var viewModel = new ClientCreateViewModel()
            {
                Facilities = await _context.Facilities.Where(c => c.UserId == user.Id).ToListAsync()
            };

            ViewData["FacilityId"] = new SelectList(viewModel.Facilities, "FacilityId", "Name");
            return View(viewModel);
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClientCreateViewModel viewModel)
        {
            var user = await GetCurrentUserAsync();
            ModelState.Remove("Client.User");
            ModelState.Remove("Client.UserId");
            viewModel.Client.User = user;
            viewModel.Client.UserId = user.Id;


            if (ModelState.IsValid)
            {
                //viewModel.Client.UserId = user.Id;
                _context.Add(viewModel.Client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusTypeId"] = new SelectList(_context.StatusTypes, "StatusTypeId", "Name", viewModel.Client.StatusTypeId);
            //ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", client.UserId);
            viewModel.Facilities = await _context.Facilities.Where(c => c.UserId == user.Id).ToListAsync();
            ViewData["FacilityId"] = new SelectList(viewModel.Facilities, "FacilityId", "Name");

            return View(viewModel);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var viewModel = new ClientInformationEditViewModel()
            {
                Facilities = await _context.Facilities.Where(c => c.UserId == user.Id).ToListAsync()
            };
            viewModel.Client = await _context.Clients.FindAsync(id);

            if (viewModel.Client == null)
            {
                return NotFound();
            }
            ViewData["StatusTypeId"] = new SelectList(_context.StatusTypes, "StatusTypeId", "Name", viewModel.Client.StatusTypeId);
            ViewData["FacilityId"] = new SelectList(viewModel.Facilities, "FacilityId", "Name");
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", viewModel.Client.UserId);
            return View(viewModel);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  ClientInformationEditViewModel viewModel)
        {
            if (id != viewModel.Client.ClientId)
            {
                return NotFound();
            }
            var user = await GetCurrentUserAsync();
            viewModel.Client.User = user;
            viewModel.Client.UserId = user.Id;
            viewModel.Client.ClientAssessmets = await _context.ClientAssessments.Where(c => c.ClientId == viewModel.Client.ClientId).ToListAsync();
            //ModelState.Remove("User");
            //ModelState.Remove("UserId");


            //if (ModelState.IsValid)
            //{
                try
                {
                    if (viewModel.Client.ClientAssessmets.Count() == 0 && viewModel.Client.StatusTypeId == 3)
                    {
                        TempData["ErrorMessage"] = "Client needs to be assessed before they can be eligible.";
                        ViewData["StatusTypeId"] = new SelectList(_context.StatusTypes, "StatusTypeId", "Name", viewModel.Client.StatusTypeId);
                        return View(viewModel);
                    }
                    else
                    {
                        _context.Update(viewModel.Client);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(viewModel.Client.ClientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            //}
            ViewData["StatusTypeId"] = new SelectList(_context.StatusTypes, "StatusTypeId", "Name", viewModel.Client.StatusTypeId);
            //ViewData["FacilityId"] = new SelectList(viewModel.Facilities, "FacilityId", "Name");
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", viewModel.Client.UserId);
                return RedirectToAction(nameof(Index));
            //return View(viewModel);
        }
        //Edit status method
        // GET: Clients/Discharge/5
        //public async Task<IActionResult> Discharge(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    var user = await _userManager.GetUserAsync(HttpContext.User);
        //    var client = new Client();
        //    client = await _context.Clients.FindAsync(id);

CaseloadManager/Controllers/GoalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CaseloadManager.Data;
using CaseloadManager.Models;

namespace CaseloadManager.Controllers
{
    public class GoalsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GoalsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Goals
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Goals.Include(g => g.Client);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Goals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goal = await _context.Goals
                .Include(g => g.Client)
                .FirstOrDefaultAsync(m => m.GoalId == id);
            if (goal == null)
            {
                return NotFound();
            }

            return View(goal);
        }

        // GET: Goals/Create
        public IActionResult Create(string ClientId)
        {
            ViewData["ClientId"] = ClientId;
            return View();
        }

        // POST: Goals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GoalId,Title,Description,ClientId")] Goal goal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(goal);
                await _context.SaveChangesAsync();
                return Redirect($"/Clients/Details/{goal.ClientId}");
                //return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = goal.ClientId;
            return View(goal);
        }

        // GET: Goals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goal = await _context.Goals.FindAsync(id);
            if (goal == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "FirstInitial", goal.ClientId);
            return View(goal);
        }

        // POST: Goals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GoalId,Title,Description,ClientId")] Goal goal)
        {
            if (id != goal.GoalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(goal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GoalExists(goal.GoalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "FirstInitial", goal.ClientId);
            return View(goal);
        }

        // GET: Goals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goal = await _context.Goals
                .Include(g => g.Client)
                .FirstOrDefaultAsync(m => m.GoalId == id);
            if (goal == null)
            {
                return NotFound();
            }

            return View(goal);
        }

        // POST: Goals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var goal = await _context.Goals.FindAsync(id);
            _context.Goals.Remove(goal);
            await _context.SaveChangesAsync();
            return Redirect($"/Clients/Details/{goal.ClientId}");
        }

        private bool GoalExists(int id)
        {
            return _context.Goals.Any(e => e.GoalId == id);
        }
    }
}

CaseloadManager/Views/Clients/Delete.cshtml
@model CaseloadManager.Models.Client

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstInitial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstInitial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birthdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diagnosis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diagnosis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SessionsPerWeek)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SessionsPerWeek)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusType.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacilityId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacilityId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClientId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CaseloadManager/Views/Clients/Details.cshtml
@model CaseloadManager.Models.ClientEditViewModel

@{
    ViewData["Title"] = "Details";
}
<style>
    .HighlightStandardizedScore {
        color: #F65c78;
    }

    .HighlightStandardizedScoreGreen {
        color: #C3F584;
    }

    .delete-section {
        display: inline;
    }
</style>

<h4>Client</h4>
<hr />

@*test for card*@
<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="~/css/userIcon.png" class="card-img" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Info</h5>
                <p class="card-text">
                    <ul class="list-group">
                        <li class="list-group-item">@Html.DisplayNameFor(model => model.Client.FullName): @Html.DisplayFor(model => model.Client.FullName)</li>
                        <li class="list-group-item">@Html.DisplayNameFor(model => model.Client.Birthdate): @Html.DisplayFor(model => model.Client.Birthdate)</li>
                        <li class="list-group-item">@Html.DisplayNameFor(model => model.Client.Facility.Name): @Html.DisplayFor(model => model.Client.Facility.Name)</li>
                        <li class="list-group-item">@Html.DisplayNameFor(model => model.Client.StatusType): @Html.DisplayFor(model => model.Client.StatusType.Name)</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>
@*test for card*@

<div class="container, client-details">
    @*<dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Client.FullName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Client.FullName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Client.Birthdate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Client.Birthdate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Client.Facility.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Client.Facility.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Client.StatusType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Client.StatusType.Name)
            </dd>
        </dl>*@
    @if (Model.Client.StatusTypeId != 1 && Model.Client.StatusTypeId != 5 && Model.Client.StatusTypeId != 4)
    {
        <div>
            <span style="text-decoration:underline">
                @Html.ActionLink("Add Assessment to Client", "Create", "ClientAssessments", new { clientId = @Model.Client.ClientId }, null)
        </div>
        <br />
    }


    @if (ViewBag.HasAssessment == "true")
    {
        <p>Test(s) Administered: </p>
        <dl class="row">
            @foreach (var item in Model.ClientAssessments)
            {
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(modelItem => item.Assessment.TestName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(modelItem => item.Assessment.TestName)
                </dd>
                @if (item.StandarizedScore < 78)
                {
                    <dt class="col-sm-2, HighlightStandardizedScore">
                        @Html.DisplayNameFor(modelItem => item.StandarizedScore)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(modelItem => item.StandarizedScore)
                    </dd>
                }
                else
                {
                    <dt class="col-sm-2, HighlightStandardizedScoreGreen">
                        @Html.DisplayNameFor(modelItem => item.StandarizedScore)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(modelItem => item.StandarizedScore)
                    </dd>
                }

                <dt class="col-sm-2">
                    @Html.DisplayNameFor(modelItem => item.DateAdministered)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(modelItem => item.DateAdministered)
                </dd>
            }
            @if (Model.Client.StatusTypeId == 2)
            {
                @*<div>
                        <a asp-action="Edit" asp-route-id="@Model.Client.ClientId">Eligible</a> |
                        <a asp-action="Edit" asp-route-id="@Model.Client.ClientId">Ineligible</a>
                    </div>*@
            }
        </dl>
        <br />
        @if (Model.Client.StatusTypeId == 3 || Model.Client.StatusTypeId == 5 && ViewBag.HasAssessment == "true")
        {

            <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Html.DisplayNameFor(model => model.Client.Diagnosis): @Html.DisplayFor(model => model.Client.Diagnosis)</li>
                    <li class="list-group-item">@Html.DisplayNameFor(model => model.Client.SessionsPerWeek): @Html.DisplayFor(model => model.Client.SessionsPerWeek)</li>
                </ul>
            </div>
            <br/>

@*old view of table with diagnosis and sessions*@
            @*<dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Client.Diagnosis)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Client.Diagnosis)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Client.SessionsPerWeek)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Client.SessionsPerWeek)
            </dd>*@

            @if (Model.Client.StatusTypeId == 3)
            {
                <div>
                    <span style="text-decoration:underline">
                        @Html.ActionLink("Add Goal to Client", "Create", "Goals", new { clientId = @Model.Client.ClientId }, null)
                </div>
                <br/>
                @if (ViewBag.HasGoal == "true")
                {
                    <p>Client Goals: </p>
                    <dl class="row">
                        @foreach (var item in Model.Client.Goals)
                        {
                            <div class="card">
                                <div class="card-header">
                                    @Html.DisplayFor(modelItem => item.Title)
                                </div>
                                <div class="card-body">
                                    <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
                                    <div class="delete-section">
                                        @Html.ActionLink("Delete Goal", "Delete", "Goals", new { id = item.GoalId }, null)
                                    </div>
                                </div>
                            </div>

                            @*<dt class="col-sm-2">
                                @Html.DisplayNameFor(modelItem => item.Title)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(modelItem => item.Title)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(modelItem => item.Description)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(modelItem => item.Description)
                            </dd>
                            <div class="delete-section">
                                @Html.ActionLink("Delete Goal", "Delete", "Goals", new { id = item.GoalId }, null)
                            </div>*@
                        }
                    </dl>
                }
                <br />
                <div>
                    <span style="text-decoration:underline">
                        @Html.ActionLink("Log a therapy session", "Create", "TherapySessions", new { clientId = @Model.Client.ClientId }, null)
                </div>
                <br />
            }
        }
    }





    <div>
        <a class="btn btn-outline-dark btn-sm" asp-action="Edit" asp-route-id="@Model.Client.ClientId">Edit</a> |
        <a class="btn btn-outline-dark btn-sm" asp-action="Index">Back to List</a>
    </div>
</div>

CaseloadManager/Views/Clients/Edit.cshtml
@model CaseloadManager.Models.ClientInformationEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Client</h1>

<hr />
<div class="edit-client_position">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Client.ClientId" />
                <div class="form-group">
                    <label asp-for="Client.FirstInitial" class="control-label"></label>
                    <input asp-for="Client.FirstInitial" class="form-control" />
                    <span asp-validation-for="Client.FirstInitial" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Client.LastName" class="control-label"></label>
                    <input asp-for="Client.LastName" class="form-control" />
                    <span asp-validation-for="Client.LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Client.Birthdate" class="control-label"></label>
                    <input asp-for="Client.Birthdate" class="form-control" />
                    <span asp-validation-for="Client.Birthdate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Client.FacilityId" class="control-label"></label>
                    <select asp-for="Client.FacilityId" class="form-control" asp-items="ViewBag.FacilityId"></select>
                </div>
                <div class="text-danger mt-2 mb-2">@TempData["ErrorMessage"] </div>
                <div class="form-group">
                    <label asp-for="Client.StatusTypeId" class="control-label"></label>
                    <select asp-for="Client.StatusTypeId" class="form-control" asp-items="ViewBag.StatusTypeId"></select>
                    <span asp-validation-for="Client.StatusTypeId" class="text-danger"></span>
                </div>
                @if (Model.Client.StatusTypeId == 3 || Model.Client.StatusTypeId == 5)
                {
                    <div class="form-group">
                        <label asp-for="Client.Diagnosis" class="control-label"></label>
                        <input asp-for="Client.Diagnosis" class="form-control" />
                        <span asp-validation-for="Client.Diagnosis" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Client.SessionsPerWeek" class="control-label"></label>
                        <input asp-for="Client.SessionsPerWeek" class="form-control" />
                        <span asp-validation-for="Client.SessionsPerWeek" class="text-danger"></span>
                    </div>
                }
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-outline-dark btn-sm" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a class="btn btn-outline-dark btn-sm" asp-controller="Clients"
       asp-action="Details"
       asp-route-id="@Model.Client.ClientId">Back to details</a>
</div>
@*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}